### PR TITLE
Added Hand Gesture Detection Feature

### LINKED ISSUE #8: File Conflicts
@Akash-Ramjyothi We are sorry to inform that the commits you made regarding the resolving conflicts have reverted due to technical issues.  We hope you can redo them, please take your time.

### PR DESCRIPTION
**Pull request by Akash-Ramjyothi**
<h1 align="center">Hand Gesture Detection</h1>

## 📜 Description:
Developed a Simple Hand Gesture Detection System to identify numbers with OpenCV. This Hand Gesture System can be used in Surveillance to alert authorities on armed robbery situations where verbal communication is not possible. Also, it can be used to control various electronic appliances without the use of a remote, just by hand gestures such as air conditioner, TV, music system, controlling computer cursor, etc.

## 📽 Sample Demo:
ezgif com-gif-maker (2)

## 🏗 Built With:
 - Numpy Library.
 - OpenCV Library.
 - OS Module.
 - Pip
 - Used .avi (Audio Video Interleave) format file as source.

## 🧪 Steps to Build locally:
- Install numpy: 
```bash
pip3 install numpy
```
- Install OpenCV: 
```bash
pip3 install opencv-python
```
- Run the Script, type: 
```bash
python3 hand.py
```

## 🌐 References Used:
- https://www.youtube.com/watch?v=QkO_3absfdw
- https://www.youtube.com/watch?v=v-XcmsYlzjA
- https://www.youtube.com/watch?v=jV4wijjvD-Y

### CODE REVIEW

**Comment by networkwithoutborders** [comment]
Appreciate your efforts! Here are a few things we noticed:

- [X] Addition of new module / improvement on existing
- [ ] Kindly follow the flow of readme (similar to the one in face_recognition), section titles are impressive
- [ ] Expand / explain in detail the steps to build (without cloning from personal repositories)
- [ ] 'Contributions' & 'Developed by' sections can be omitted for now
- [ ] Relevancy of module with surveillance system can be highlighted

PS: Please acknowledge once the changes are made, the PR will be merged then!

**Comment by Akash-Ramjyothi** [comment]
@Surveillance-NWB thank you so much for pointing out the changes that have to be made. I have made the changes. Can you please review it?

**Comment by networkwithoutborders** [comment]
Appreciate your efforts! We notice that the commits have conflicts.  We hope you work on rectifying them.  Further,

- [X] Addition of new module / improvement on existing
- [X] Kindly follow the flow of readme (similar to the one in face_recognition), section titles are impressive
- [X] Expand / explain in detail the steps to build (without cloning from personal repositories)
- [X] 'Contributions' & 'Developed by' sections can be omitted for now
- [X] Relevancy of module with surveillance system can be highlighted

PS: Please acknowledge once the changes are made, the PR will be merged then!

**Comment by Akash-Ramjyothi** [comment]
@Surveillance-NWB Thank you so much for pointing out the required change. I have resolved it. Can you please review my PR?

**Comment by Akash-Ramjyothi** [comment]
@Surveillance-NWB @Kavyapriyakp Please review, I have resolved the commit.

**Comment by Akash-Ramjyothi** [comment]
@Surveillance-NWB @Kavyapriyakp Please review.

**Pull request merged**
