### PR TITLE
Adding Person Counting feature

### LINKED ISSUE #5: Readme conflicts
@adityamukherjee42 We notice that the readme for the modules you have developed has overlapped with the readme of the repository. Kindly do the neeful at the earliest!

### PR DESCRIPTION
**Pull request by adityamukherjee42**
<h1 align="center">Person Counter</h1>

## Description:
It is a very quick implementation of counting the number of people in a room using a Mobilenet SSD detector.This can help in the Surveillance and especially in a covid time where there should not be more than a certain amount of people in the room.

## Table of contents
* [About the Modules](#About-the-Modules)
* [Surveillence Usecase](#Surveillence-Usecase)
* [Setup](#Setup)
* [Demo](#Demo)

## About the Modules:
The Modules used here mainly are:
<ul>
<liOpencv</li>
<li>imutills</li>
<li>Numpy</li>
</ul>
We make use of a single-shot detection algorithm for the detection of humans that are present in the room. A single Shot detector like YOLO takes only one shot to detect multiple objects present in an image using a multi-box. It is significantly faster in speed and high-accuracy object detection algorithm. SSD also fits our requirements of high fps and lightweight python program 

## Surveillance Usecase:
During these times of Covid, it is a must to follow the SOP and curb the chain of transmission. In this one of the main Protocols to be followed is Social distancing and not overcrowding any rooms. The Person Counting code  will help us in the Surveillance of whether the room is overcrowded or not and thus keep an eye on whether the SOPS are being followed and then curb the spread of COIVD  

## Setup
To run this project locally:
Go to the directory where the project is present

Write this in your Command prompt
```
$pip -r rquirements.txt

```

Then after this in the command prompt and use this command
```
$ python Person_Counter.py

```

## Demo
video

### CODE REVIEW

**Comment by networkwithoutborders** [comment]
Appreciate your efforts! Here are a few things we noticed:

- [X] Addition of new module / improvement on existing
- [ ] Good flow of readme, but we notice that a few more sections can be added ( kindly look into readme of face_recognition module)
- [ ] Relevancy of module with surveillance system can be highlighted
- [ ] Please mention the output demo/gif/video/image for easy evaluation 

PS: Please acknowledge once the changes are made, the PR will be merged then! Great work!

**Comment by adityamukherjee42** [comment]
Hey, thank you for the kind words, I have updated the readme as required  please look into it and see weather further improvements are needed

**Comment by networkwithoutborders** [comment]
> Hey, thank you for the kind words, I have updated the readme as required please look into it and see weather further improvements are needed

Appreciate the immediate actions!  We notice the following:
- [X] Addition of new module / improvement on existing
- [X] Good flow of readme, but we notice that a few more sections can be added ( kindly look into readme of face_recognition module)
- [X] Relevancy of module with surveillance system can be highlighted
- [X] Please mention the output demo/gif/video/image for easy evaluation 
- [ ] 'Contributor' section can be omitted for now

PS: Please acknowledge once the changes are made, the PR will be merged then! All the best!

**Comment by adityamukherjee42** [comment]
Hey,, I have removed rhe contribution as asked to , thanks!

**Comment by networkwithoutborders** [comment]
> Hey,, I have removed rhe contribution as asked to , thanks!

Thank you for your interest, we appreciate the efforts!  We notice the following:
- [X] Addition of new module / improvement on existing
- [X] Good flow of readme, but we notice that a few more sections can be added ( kindly look into readme of face_recognition module)
- [X] Relevancy of module with surveillance system can be highlighted
- [X] Please mention the output demo/gif/video/image for easy evaluation 
- [X] 'Contributor' section can be omitted for now

All the best!

**Pull request merged**
