### PR TITLE
Added Eye Tracking Feature

### PR DESCRIPTION
**Pull request by Akash-Ramjyothi**
<h1 align="center">Advanced Eye Tracking</h1>

## 📜 Description:
Developed an advanced eye-tracking system with OpenCV and data extracted from a recorded .flv file. The program bounds the box of the iris and scales on the axis. The Eye-Tracking can be used in Surveillance to see if the user is seeing a screen such as TV or not. If the user is not seeing the screen, it can show up a message that User is inactive. In further scaling, it can also be used to monitor workload of a user doing a particular task.

## 📽 Sample Demo:
ezgif com-gif-maker (3)

## 🏗 Built With:
 - Numpy Library.
 - OpenCV Library.
 - Pip
 - Used .flv (Flash Video) format file as source.

## 🧪 Steps to Build locally:
- Install numpy: 
```bash
pip3 install numpy
```
- Install OpenCV: 
```bash
pip3 install opencv-python
```
- Run the Script, type: 
```bash
python3 eye_motion_tracking.py
```

## 🌐 References Used:
- https://www.youtube.com/watch?v=YEZMk1P0-yw
- https://www.youtube.com/watch?v=kbdbZFT9NQI
- https://www.youtube.com/watch?v=mPCZLOVTEc4

### CODE REVIEW

**Comment by networkwithoutborders** [comment]
Appreciate your efforts! Here are a few things we noticed:

- [X] Addition of new module / improvement on existing
- [ ] Kindly follow the flow of readme (similar to the one in face_recognition), section titles are impressive
- [ ] Expand / explain in detail the steps to build (without cloning from personal repositories)
- [ ] 'Contributions' & 'Developed by' sections can be omitted for now
- [ ] Relevancy of module with surveillance system can be highlighted

PS: Please acknowledge once the changes are made, the PR will be merged then!

**Comment by networkwithoutborders** [comment]
@Akash-Ramjyothi This is a friendly reminder to update the PR. The evaluation will happen EOD.

**Comment by Akash-Ramjyothi** [comment]
@Surveillance-NWB thank you so much for pointing out the changes that have to be made. I have made the changes. Can you please review it?

**Comment by networkwithoutborders** [comment]
Appreciate your efforts! We notice that the commits have conflicts.  We hope you work on rectifying them.  Further,

- [X] Addition of new module / improvement on existing
- [X] Kindly follow the flow of readme (similar to the one in face_recognition), section titles are impressive
- [X] Expand / explain in detail the steps to build (without cloning from personal repositories)
- [X] 'Contributions' & 'Developed by' sections can be omitted for now
- [X] Relevancy of module with surveillance system can be highlighted

PS: Please acknowledge once the changes are made, the PR will be merged then!

**Comment by Akash-Ramjyothi** [comment]
@Surveillance-NWB Thank you so much for pointing out the required change. I have resolved it. Can you please review my PR?

**Comment by Akash-Ramjyothi** [comment]
@Surveillance-NWB @Kavyapriyakp Please review, I have resolved the commit.

**Comment by networkwithoutborders** [comment]
Appreciate the efforts!

**Pull request merged**
